### PR TITLE
Adding video link & updating the summary of visualizations

### PR DESCRIPTION
**Pull request by sasinikm**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Adding video link & updating the summary of visualizations
## What did you learn from the changes you have made?
NA
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
NA
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
NA
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by yevheniia-shabalova — APPROVED** [review]
@sasinikm please check the access to your video recording. It requires to request the access. Thank you. No other comments ☺️

**Comment by sasinikm** [comment]
It is fixed now. Thank you.

**Review by OlgaKt — APPROVED** [review]
Great video!

**Review by OlhaZam — APPROVED** [review]
Great!

**Pull request merged**
