### PR TITLE
Adding summary of visualizations to Readme file

### PR DESCRIPTION
**Pull request by sasinikm**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Adding summary of visualizations to Readme file
## What did you learn from the changes you have made?
How to provide insights based on visualizations for business decision making
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by yevheniia-shabalova — APPROVED** [review]
Approved. Good summary.

**Comment by yevheniia-shabalova** [comment]
@sasinikm There are some merge conflicts. Could you please take a look on that? If you need assistance let me know.

**Review by OlhaZam — APPROVED** [review]
Looks great

**Review by OlgaKt — APPROVED** [review]
Great summary!

**Pull request merged**
