### PR TITLE
Changes to README file (added sections)

### PR DESCRIPTION
**Pull request by yevheniia-shabalova**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)

- Returned and renamed old readme file
- Added sections for README file (Conclusions and Suggestions)

## What did you learn from the changes you have made?

-

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?

-

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?

-

## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by OlhaZam — COMMENTED** [review]
The readme file is awesome! Well structured and organized.
The only comment, can you please change the store size to CPI (CPI – Prevailing consumer price index)?
Thanks

**Comment by sasinikm** [comment]
Readme file looks good to me. The only suggested change is to replace 'store size' with 'CPI' as @OlhaZam mentioned.
Thanks.

**Review by OlgaKt — COMMENTED** [review]
Looks good. Thank you.

**Review by sasinikm — CHANGES_REQUESTED** [review]
Readme file looks good to me. The only suggested change is to replace 'store size' with 'CPI' as @OlhaZam mentioned.
Thanks.

**Review by sasinikm — APPROVED** [review]
Looks good, well-structured.
Thank you

**Pull request merged**
